name: kuron_crotpedia
description: Crotpedia source implementation for Kuron app
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  kuron_core:
    path: ../kuron_core
  dio: ^5.9.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  html: ^0.15.4
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.8
  mockito: ^5.4.4
  build_runner: ^2.4.13
