name: kuron_nhentai
description: nhentai source implementation for Kuron app
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  kuron_core:
    path: ../kuron_core
  dio: ^5.9.0
  html: ^0.15.4
  logger: ^2.6.2

dev_dependencies:
  flutter_lints: ^6.0.0
