name: kuron_core
description: Core interfaces and entities for Kuron multi-source content app
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
